spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: demo_user
    password: ${DEMODB_DEMOUSER_PASSWORD}
  main:
    log-startup-info: false
  devtools:
    restart:
      enabled: true
