packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@types/node": 22.15.12
  "@vitest/coverage-v8": 3.1.3
  "knip": 5.53.0
  "orval": 7.9.0
  "prettier": 3.5.3
  "prettier-plugin-java": 2.6.7
  "typescript": 5.8.3
  "vitest": 3.1.3
catalogs:
  web:
    "httpxy": 0.1.7
    "react": 19.1.0
    "react-dom": 19.1.0
    "next": 15.3.1
    "nuqs": 2.4.3
    "@types/react": 19.1.3
    "@types/react-dom": 19.1.3
