packages:
  - apps/web-form
  - apps/web-tool

catalog:
  "@biomejs/biome": 2.3.5
  "@hey-api/openapi-ts": 0.87.4
  "@mantine/core": 8.3.7
  "@mantine/hooks": 8.3.7
  "@types/node": 24.10.1
  "@types/react": 19.2.4
  "@types/react-dom": 19.2.3
  "@vitest/coverage-v8": 4.0.8
  httpxy: 0.1.7
  knip: 5.69.1
  next: 16.0.3
  nuqs: 2.7.3
  postcss: 8.5.6
  postcss-preset-mantine: 1.18.0
  postcss-simple-vars: 7.0.1
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
  vitest: 4.0.8
  wireit: 0.14.12

catalogMode: strict

injectWorkspacePackages: true

managePackageManagerVersions: true

syncInjectedDepsAfterScripts:
  - build

useNodeVersion: 24.5.0
