packages:
  - apps/web-form
  - apps/web-tool

catalog:
  "@biomejs/biome": 2.2.7
  "@hey-api/openapi-ts": 0.86.2
  "@mantine/core": 8.3.5
  "@mantine/hooks": 8.3.5
  "@types/node": 24.9.1
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2
  "@vitest/coverage-v8": 4.0.3
  httpxy: 0.1.7
  knip: 5.66.2
  next: 16.0.0
  nuqs: 2.7.2
  postcss: 8.5.6
  postcss-preset-mantine: 1.18.0
  postcss-simple-vars: 7.0.1
  react: 19.2.0
  react-dom: 19.2.0
  typescript: 5.9.3
  vitest: 4.0.3
  wireit: 0.14.12

catalogMode: strict

injectWorkspacePackages: true

managePackageManagerVersions: true

syncInjectedDepsAfterScripts:
  - build

useNodeVersion: 24.5.0
