packages:
  - apps/web-form
  - apps/web-tool

catalog:
  "@biomejs/biome": 2.3.10
  "@hey-api/openapi-ts": 0.89.1
  "@mantine/core": 8.3.10
  "@mantine/hooks": 8.3.10
  "@types/node": 24.10.4
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  "@vitest/coverage-v8": 4.0.16
  httpxy: 0.1.7
  knip: 5.75.1
  next: 16.1.0
  nuqs: 2.8.5
  postcss: 8.5.6
  postcss-preset-mantine: 1.18.0
  postcss-simple-vars: 7.0.1
  react: 19.2.3
  react-dom: 19.2.3
  typescript: 5.9.3
  vitest: 4.0.16
  wireit: 0.14.12

catalogMode: strict

injectWorkspacePackages: true

managePackageManagerVersions: true

syncInjectedDepsAfterScripts:
  - build

useNodeVersion: 24.5.0
