packages:
  - apps/web-form
  - apps/web-tool

catalog:
  "@biomejs/biome": 2.4.15
  "@hey-api/openapi-ts": 0.97.2
  "@tanstack/react-router": 1.170.7
  "@tanstack/react-start": 1.168.10
  "@tailwindcss/vite": 4.3.0
  "@types/node": 24.12.4
  "@types/react": 19.2.15
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": 6.0.2
  "@vitest/coverage-v8": 4.1.7
  knip: 6.14.1
  pino: 10.3.1
  react: 19.2.6
  react-dom: 19.2.6
  tailwindcss: 4.3.0
  temporal-polyfill-lite: 0.3.6
  typescript: 6.0.3
  vite: 8.0.14
  vitest: 4.1.7
  wireit: 0.14.12
  zod: 4.4.3

catalogMode: strict

injectWorkspacePackages: true

managePackageManagerVersions: true

syncInjectedDepsAfterScripts:
  - build

useNodeVersion: 25.9.0
