packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@types/node": 22.13.10
  "@vitest/coverage-v8": 3.0.4
  "knip": 5.43.6
  "orval": 7.4.1
  "prettier": 3.4.2
  "prettier-plugin-java": 2.6.7
  "typescript": 5.7.3
  "vitest": 3.0.4
catalogs:
  web:
    "httpxy": 0.1.7
    "react": 19.0.0
    "react-dom": 19.0.0
    "next": 15.1.7
    "nuqs": 2.3.2
    "@types/react": 19.0.8
    "@types/react-dom": 19.0.3
