packages:
  - apps/web-form
  - apps/web-tool

catalog:
  "@biomejs/biome": 2.4.11
  "@hey-api/openapi-ts": 0.95.0
  "@tailwindcss/vite": 4.2.2
  "@types/node": 24.12.2
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@vitejs/plugin-react": 6.0.1
  "@vitest/coverage-v8": 4.1.4
  knip: 6.4.0
  pino: 10.3.1
  react: 19.2.5
  react-dom: 19.2.5
  # renovate: ignore
  spiceflow: 1.18.0-rsc.29
  tailwindcss: 4.2.2
  temporal-polyfill-lite: 0.3.3
  typescript: 6.0.2
  vite: 8.0.8
  vitest: 4.1.4
  wireit: 0.14.12
  zod: 4.3.6

catalogMode: strict

injectWorkspacePackages: true

managePackageManagerVersions: true

syncInjectedDepsAfterScripts:
  - build

useNodeVersion: 25.9.0
