packages:
  - apps/web-form
  - apps/web-tool

catalog:
  "@biomejs/biome": 2.3.15
  "@hey-api/openapi-ts": 0.92.3
  "@mantine/core": 8.3.14
  "@mantine/hooks": 8.3.14
  "@types/node": 24.10.13
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@vitest/coverage-v8": 4.0.18
  httpxy: 0.3.0
  knip: 5.83.1
  next: 16.1.6
  nuqs: 2.8.8
  postcss: 8.5.6
  postcss-preset-mantine: 1.18.0
  postcss-simple-vars: 7.0.1
  react: 19.2.4
  react-dom: 19.2.4
  typescript: 5.9.3
  vitest: 4.0.18
  wireit: 0.14.12

catalogMode: strict

injectWorkspacePackages: true

managePackageManagerVersions: true

syncInjectedDepsAfterScripts:
  - build

useNodeVersion: 24.13.0
