packages:
  - frontend/*

catalog:
  "@biomejs/biome": 2.1.4
  "@types/node": 24.2.1
  "@types/react": 19.1.10
  "@types/react-dom": 19.1.7
  "@vitest/coverage-v8": 3.2.4
  httpxy: 0.1.7
  knip: 5.62.0
  next: 15.4.6
  nuqs: 2.4.3
  orval: 7.11.2
  react: 19.1.1
  react-dom: 19.1.1
  typescript: 5.9.2
  vitest: 3.2.4
  wireit: 0.14.12

catalogMode: strict

injectWorkspacePackages: true

managePackageManagerVersions: true

syncInjectedDepsAfterScripts:
  - build

useNodeVersion: 24.5.0
