packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@types/node": 22.16.4
  "@vitest/coverage-v8": 3.2.4
  "knip": 5.61.3
  "orval": 7.10.0
  "typescript": 5.8.3
  "vitest": 3.2.4
catalogs:
  web:
    "httpxy": 0.1.7
    "react": 19.1.0
    "react-dom": 19.1.0
    "next": 15.4.5
    "nuqs": 2.4.3
    "@types/react": 19.1.8
    "@types/react-dom": 19.1.6
