packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@types/node": 22.15.30
  "@vitest/coverage-v8": 3.2.2
  "knip": 5.60.2
  "orval": 7.9.0
  "prettier": 3.5.3
  "prettier-plugin-java": 2.6.8
  "typescript": 5.8.3
  "vitest": 3.2.2
catalogs:
  web:
    "httpxy": 0.1.7
    "react": 19.1.0
    "react-dom": 19.1.0
    "next": 15.3.3
    "nuqs": 2.4.3
    "@types/react": 19.1.6
    "@types/react-dom": 19.1.6
