packages:
  - apps/web-form
  - apps/web-tool

catalog:
  "@biomejs/biome": 2.1.4
  "@hey-api/openapi-ts": 0.83.1
  "@types/node": 24.2.1
  "@types/react": 19.1.9
  "@types/react-dom": 19.1.7
  "@vitest/coverage-v8": 3.2.4
  httpxy: 0.1.7
  knip: 5.62.0
  next: 15.5.2
  nuqs: 2.4.3
  react: 19.1.1
  react-dom: 19.1.1
  typescript: 5.9.2
  vitest: 3.2.4
  wireit: 0.14.12

catalogMode: strict

injectWorkspacePackages: true

managePackageManagerVersions: true

syncInjectedDepsAfterScripts:
  - build

useNodeVersion: 24.5.0
