packages:
  - apps/*
catalog:
  "@biomejs/biome": 1.9.4
  "@types/node": 22.13.14
  "@vitest/coverage-v8": 3.0.9
  "knip": 5.46.4
  "orval": 7.7.0
  "prettier": 3.5.3
  "prettier-plugin-java": 2.6.7
  "typescript": 5.8.2
  "vitest": 3.0.9
catalogs:
  web:
    "httpxy": 0.1.7
    "react": 19.1.0
    "react-dom": 19.1.0
    "next": 15.2.4
    "nuqs": 2.4.1
    "@types/react": 19.0.12
    "@types/react-dom": 19.0.4
