spring:
  application:
    name: demo-api
  profiles:
    active:
      - local
  main:
    banner-mode: "off"
  web:
    resources:
      add-mappings: false
  mvc:
    problemdetails:
      enabled: true
    contentnegotiation:
      media-types:
        csv: text/csv
  lifecycle:
    timeout-per-shutdown-phase: 20s
server:
  port: 8080
  shutdown: graceful
mybatis:
  configuration:
    map-underscore-to-camel-case: true
# logging:
#   structured:
#     format:
#       console: logstash
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
  metrics:
    distribution:
      percentiles:
        "[http.server.requests]":
          - 0.99
          - 0.999
  server:
    port: 8081
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
