spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: app
    password: app
  main:
    log-startup-info: false
  devtools:
    restart:
      enabled: true
springdoc:
  api-docs:
    path: /spec/openapi.json
  swagger-ui:
    path: /spec
