spring:
  application:
    name: demo-api
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: app
    password: app
springdoc:
  api-docs:
    path: /spec/openapi.json
  swagger-ui:
    path: /spec
