name: ci

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

env:
  CI: true
  TZ: Asia/Tokyo
  DO_NOT_TRACK: 1

jobs:
  check-gradle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      - run: ./gradlew clean spotlessCheck build test
  check-pnpm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1
      - run: pnpm --version
      - run: node --version
      - run: pnpm run check
