name: ci

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

env:
  CI: true
  TZ: Asia/Tokyo
  DO_NOT_TRACK: 1

jobs:
  check-gradle:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: gradle/actions/wrapper-validation@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      - run: ./gradlew clean spotlessCheck build test
  check-pnpm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2
      - run: pnpm --version
      - run: node --version
      - run: pnpm run check
